# pyTorch tutorials
Taken from the official website.

In [11]:
import torch
import numpy as np

## Essentials
### Creating empty tensors

In [12]:
vuoto1 = torch.empty(5, 3)  # creates a 5-by-3 empty tensor
print(vuoto1)

random1 = torch.rand(5, 3)  # creates a 5-by-3 random tensor
print(random1)

zeros1 = torch.zeros(10, 2)  # creates a 10-by-2 zeroed tensor
print(zeros1)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.3314, 0.6105, 0.1927],
        [0.6066, 0.6493, 0.7359],
        [0.7485, 0.2916, 0.3296],
        [0.4770, 0.6908, 0.0363],
        [0.7803, 0.8376, 0.9116]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


### Constructing a tensor from data

In [13]:
# To construct a tensor from data, we can do:
from_data1 = torch.tensor([10, 20.3, 2])
print(from_data1)

# We can specify the type of data we want
from_data2 = torch.tensor([10, 20.3, 2], dtype=torch.long)
print(from_data2)

from_data3 = torch.tensor([10, 20.3, 2], dtype=torch.double)
print(from_data3)

tensor([10.0000, 20.3000,  2.0000])
tensor([10, 20,  2])
tensor([10.0000, 20.3000,  2.0000], dtype=torch.float64)


### Converting other data types to tensors

In [14]:
# Or it is possible to "convert" and reuse other tensors as well
from_data4 = from_data3.new_empty(10, 2)
print(from_data4)
from_data5 = torch.randn_like(from_data1, dtype=torch.float)
print(from_data5)

# To obtain tensor size:
print(from_data5.size())
print(from_data4.size())

tensor([[2.2338e-314,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [2.8510e-315,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00, 1.6955e-308]], dtype=torch.float64)
tensor([0.7554, 0.2827, 0.3302])
torch.Size([3])
torch.Size([10, 2])


## Operations on tensors

In [15]:
random2 = torch.randn_like(random1)
print(random1 + random2)  # Sum of tensors
print(torch.add(random1, random2))  # Another way, explicit method call
risultato_somma = torch.empty_like(random1)  # Another way, involving pre-initializing the result storage tensor
torch.add(random1, random2, out=risultato_somma)
print(risultato_somma)
random3 = torch.randn_like(random1)
random3.add_(random2)  # In place addition, will add random2 to random3, and reassign the result

# Tensors support all the NumPy-like indexing facilities:
print(random1[:, 1])

# Also to reshape, it's possible to use the torch.view() methods:
x1 = torch.randn(4, 4)  # 4 by 4 random tensor, size == 16
y1 = x1.view(16)  # now, the same elements are arranged as a 16 (by 1) tensor
z1 = x1.view(-1, 8)  # ask to put 8 elements on the second dimension and to infer how many it needs to put in the first (-1)
z2 = x1.view(-1, 2, 2)  # now let's ask to do a 3-D tensor with 2 elements on the second dimension and 2 elements on the third dimension, let's allow torch to infer how many elementds it should put on the remaining (1st) dimension
print(x1.size(), y1.size(), z1.size())
print()
print(z2, z2.size())

tensor([[ 0.2404,  1.1186,  0.6777],
        [ 0.7435,  0.8598,  0.7837],
        [-0.7004, -0.8703, -0.1228],
        [-0.1182,  1.5795, -0.8086],
        [ 1.0237,  0.9654, -0.0428]])
tensor([[ 0.2404,  1.1186,  0.6777],
        [ 0.7435,  0.8598,  0.7837],
        [-0.7004, -0.8703, -0.1228],
        [-0.1182,  1.5795, -0.8086],
        [ 1.0237,  0.9654, -0.0428]])
tensor([[ 0.2404,  1.1186,  0.6777],
        [ 0.7435,  0.8598,  0.7837],
        [-0.7004, -0.8703, -0.1228],
        [-0.1182,  1.5795, -0.8086],
        [ 1.0237,  0.9654, -0.0428]])
tensor([0.6105, 0.6493, 0.2916, 0.6908, 0.8376])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])

tensor([[[-2.0984, -0.1755],
         [-0.0574, -0.8822]],

        [[-2.0499,  0.1235],
         [ 0.4347,  0.2399]],

        [[-1.0024,  0.6114],
         [ 0.1473,  1.0681]],

        [[-1.2728,  0.1387],
         [-0.6172, -1.1033]]]) torch.Size([4, 2, 2])


The command ```torch.view()``` can be used to resize/reshape tensors (by selecting the desired elements) by asking it to 
rearrange the elements so that they fit in the requested size/dimensions.

In [16]:
# For a singleton tensor, we can get the value as a normal number with:
singleton1 = torch.randn(1)
print(singleton1)
print(singleton1.item())

tensor([0.2163])
0.21630989015102386


We can use the ```torch.item()``` method to extract the actual element from the tensor, as seen above.

## Numpy integration

In [17]:
a1 = torch.ones(10)
print(a1)
a1_numpy = a1.numpy()  # To convert to a NumPy array
print(a1_numpy)

# Let's see what happens with:
a1.add_(1)
print(a1)
print(a1_numpy)  # it carries the change from the tensor to the NumPy array

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


Any operator which mutates directly the original variable (like in the example above) is post-fixed with a "_" symbol.

In [18]:
# And the contrary is doable, too
numpy_a1 = np.ones(10)
from_numpy_a1 = torch.from_numpy(numpy_a1)
np.add(numpy_a1, 1, out=numpy_a1)
print(numpy_a1)
print(from_numpy_a1)

[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA tensors
To take advantage of a GPU with CUDA support, we should "address" the tensors to the correct device, like shown below. 

In [19]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x1, device=device)  # directly create a tensor on GPU
    x1 = x1.to(device)                       # or just use strings ``.to("cuda")``
    z = x1 + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
else:
    print("CUDA not available on this machine/setup")

CUDA not available on this machine/setup


# Autograd: automatic differentiation
By setting a tensor's attribute ```.required_grad``` as ```True```, the operations done on the tensor will be tracked 
automatically. To halt the tracking, we can call the ```.detach()``` method and future operations on the tensor will not
be tracked. To temporarily perform untracked operations on a tensor that is being tracked, we can wrap the computations
within a ```with torch.no_grad():``` block.
Every tensor has a a reference to a function that has created the tensor, ```.grad_fn``` (except for user-made tensors, 
whose ```grad_fn``` is ```None```.
Let's try this.

In [20]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
# Let's perform an operation on this tensor.
y = x + 2
print(y)
# Given that the tensor y was created through an operation, it has a grad_fn attached.
print(y.grad_fn)
print(x.grad_fn)  # But a user-made tensor, on the other hand, has None as it's grad_fn
z = y * y * 3
out = z.mean()
print(x, out)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
None
tensor([[1., 1.],
        [1., 1.]], requires_grad=True) tensor(27., grad_fn=<MeanBackward0>)
